import {Bot,ChevronLeft,ChevronRight,ImageOff,Plus,Search,Trash2} from 'lucide-react';
import {useEffect,useMemo,useState} from 'react';
function Cover({bot}){const [failed,setFailed]=useState(false);return bot.cover&&!failed?<img className="bot-cover" src={bot.cover} alt={`${bot.name} 的封面`} onError={()=>setFailed(true)}/>:<span className="bot-cover fallback"><ImageOff size={14}/></span>}
export function BotLibrary({bots,currentBotId,onClose,onCreate,onSelect,onDelete}){
  const [query,setQuery]=useState('');
  useEffect(()=>{const onKeyDown=event=>{if(event.key==='Escape')onClose();};window.addEventListener('keydown',onKeyDown);return()=>window.removeEventListener('keydown',onKeyDown);},[onClose]);
  const filtered=useMemo(()=>bots.filter(bot=>`${bot.name} ${bot.intro} ${(bot.tags||[]).join(' ')}`.toLowerCase().includes(query.toLowerCase())),[bots,query]);
  return <><button type="button" className="bot-library-scrim" aria-label="关闭 Bot 库" onClick={onClose}/><aside className="bot-library-rail" aria-label="Bot 库"><header><button className="bot-library-back" onClick={onClose} aria-label="关闭 Bot 库"><ChevronLeft size={17}/></button><div><span>BOT LIBRARY</span><h2>我的 Bot</h2></div></header><div className="bot-library-search"><Search size={15}/><input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索 Bot"/></div><button className="bot-library-create" onClick={onCreate}><Plus size={15}/>新建 Bot</button><p className="bot-library-label">{query?`搜索结果 · ${filtered.length}`:`全部 Bot · ${bots.length}`}</p><div className="bot-library-list">{filtered.length?filtered.map(bot=><article className={`bot-library-row ${bot.id===currentBotId?'current':''}`} key={bot.id}><button className="bot-library-select" onClick={()=>onSelect(bot)}><Cover bot={bot}/><span className="bot-library-copy"><b title={bot.name}>{bot.name}</b><small title={bot.intro||'尚未填写简介'}>{bot.intro||'尚未填写简介'}</small></span><ChevronRight size={15}/></button><button className="bot-library-delete" onClick={()=>onDelete(bot)} aria-label={`删除 ${bot.name}`}><Trash2 size={14}/></button></article>):<div className="bot-library-empty"><Bot size={20}/><b>还没有匹配的 Bot</b><small>调整搜索条件，或创建一个新的。</small></div>}</div></aside></>
}
