import {Check,ChevronLeft,ChevronRight,Code2,Expand,FileText,FolderOpen,GripVertical,Image,Maximize2,Minimize2,PanelRight,Play,Plus,Settings2,SlidersHorizontal,Upload,UserRound,X} from 'lucide-react';
import {useEffect,useRef,useState} from 'react';
import {api} from '../api';
const meta={bot_basic:{label:'基础信息',icon:UserRound},bot_content:{label:'内容设定',icon:FileText},bot_advanced:{label:'高级设置',icon:SlidersHorizontal},image:{label:'图片',icon:Image},image_library:{label:'图片资源',icon:Image},text:{label:'文本',icon:FileText},code:{label:'代码',icon:Code2},file:{label:'文件',icon:FileText},other:{label:'其他',icon:Settings2}};
const tagOptions=['Romance','Drama','Forced Marriage','Comedy','Slice of Life','Dark Romance','School','Coming of Age','Conflict','Family','BL','Betrayal','Supernatural','Friendship','Horror','Crime','Possessive','Loyal','Protective','Playful','Secretive','Flirty','Emotional','Arrogant','Teasing','Violent','Dominant','Jealous','Affectionate','Gentle','Manipulative','Slow Burn','Introverted','Healthy','Grief'];
const renderData=value=>typeof value==='string'?value:value==null?'暂无可预览内容':JSON.stringify(value,null,2);
function markdownSections(value=''){return String(value).split('\n').map((line,index)=>{const hit=line.match(/^(#{1,3})\s+(.+?)\s*$/);return hit?{level:hit[1].length,title:hit[2].replace(/[*`]/g,''),id:`content-section-${index}`,line,index}:{level:0,title:line,id:`content-line-${index}`,line,index};});}
function ContentPreviewModal({content,onChange,onClose}){const editorRef=useRef(null);const sections=markdownSections(content).filter(section=>section.level);useEffect(()=>{const onKey=event=>{if(event.key==='Escape')onClose();};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[onClose]);const jump=section=>{const textarea=editorRef.current;if(!textarea)return;const before=String(content||'').split('\n').slice(0,section.index).join('\n');const position=before.length+(section.index?1:0);textarea.focus();textarea.setSelectionRange(position,position);const lineHeight=parseFloat(getComputedStyle(textarea).lineHeight)||24;textarea.scrollTop=Math.max(0,(section.index-2)*lineHeight);};return <div className="content-preview-backdrop" role="dialog" aria-modal="true" aria-label="编辑内容设定" onMouseDown={onClose}><section className="content-preview-modal" onMouseDown={event=>event.stopPropagation()}><header><div><span>CONTENT SETTING · LOCAL DRAFT</span><h2>编辑内容设定</h2></div><div><small>修改仅保存到草稿</small><button type="button" onClick={onClose} aria-label="关闭内容设定编辑"><X size={18}/></button></div></header><div className="content-preview-body"><aside className="content-toc"><b>目录</b>{sections.length?sections.map(section=><button type="button" className={`level-${section.level}`} key={section.id} onClick={()=>jump(section)}>{section.title}</button>):<small>使用 #、## 或 ### 添加目录标题。</small>}</aside><main><textarea ref={editorRef} className="content-markdown-editor" value={content} onChange={event=>onChange(event.target.value)} spellCheck="false" placeholder={'使用 Markdown 编写内容设定\n\n# 核心设定\n## 互动规则\n## 开场场景'}/></main></div></section></div>}

function TagsField({tags,onChange}){const [open,setOpen]=useState(false);const [selected,setSelected]=useState(tags||[]);const toggle=tag=>setSelected(current=>current.includes(tag)?current.filter(value=>value!==tag):current.length<5?[...current,tag]:current);const apply=()=>{onChange(selected);setOpen(false)};return <><button type="button" className="tag-field" onClick={()=>{setSelected(tags||[]);setOpen(true)}}><span>{tags?.length?tags.join(' · '):'选择标签，描述题材、特质与氛围'}</span><ChevronRight size={17}/></button>{open&&<div className="tag-picker-backdrop"><section className="tag-picker" role="dialog" aria-modal="true" aria-label="选择标签"><header><div><span>最多选择 5 个</span><h3>Tags</h3></div><button type="button" onClick={()=>setOpen(false)} aria-label="关闭标签选择"><X size={18}/></button></header><div className="tag-options">{tagOptions.map(tag=><button type="button" className={selected.includes(tag)?'selected':''} onClick={()=>toggle(tag)} key={tag}>{selected.includes(tag)&&<Check size={13}/>} {tag}<span>{selected.includes(tag)?'−':'+'}</span></button>)}</div><footer><span>{selected.length}/5 已选择</span><button type="button" onClick={apply}>确认标签</button></footer></section></div>}</>}
function Visibility({value,onChange}){return <div className="visibility-field"><p>可见范围 <em>*</em></p><div><button type="button" className={value==='public'?'selected':''} onClick={()=>onChange('public')}><span><b>公开</b><small>其他人可以发现并使用</small></span>{value==='public'&&<Check size={16}/>}</button><button type="button" className={value==='private'?'selected':''} onClick={()=>onChange('private')}><span><b>私有</b><small>仅自己可见和编辑</small></span>{value==='private'&&<Check size={16}/>}</button></div></div>}
function CoverField({value,onChange,onPreview,highlighted=false}){const [broken,setBroken]=useState(false);const [uploading,setUploading]=useState(false);const preview=String(value||'').trim();const upload=async event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;setUploading(true);try{const data_url=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});const {attachment}=await api.uploadImage({name:file.name,mime_type:file.type,data_url});setBroken(false);onChange(attachment.url);}finally{setUploading(false);}};return <label className={'cover-field '+(highlighted?'cover-field-staged':'')}><span>封面</span><div className="cover-field-row"><button type="button" className={'cover-field-preview '+(!preview||broken?'empty':'')} onClick={()=>preview&&!broken&&onPreview?.(preview)} title={preview?'查看大图':'尚未设置封面'}>{preview&&!broken?<img src={preview} alt="Bot 封面预览" onError={()=>setBroken(true)}/>:<Image size={18}/>}</button><div><input className="cover-file-input" type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={upload}/><button type="button" className="cover-upload" onClick={event=>event.currentTarget.previousElementSibling?.click()} disabled={uploading}><Upload size={13}/>{uploading?'上传中…':preview?'更换封面':'上传封面'}</button><small>上传后仅替换本地草稿预览；确认保存后才更新 Bot 封面。</small></div></div></label>}
function Basic({bot,onChange,onPreview}){return <div className="artifact-form"><CoverField value={bot.cover} onChange={value=>onChange('cover',value)} onPreview={onPreview}/><label>名称<input value={bot.name} onChange={e=>onChange('name',e.target.value)}/></label><label>简介<textarea value={bot.intro} onChange={e=>onChange('intro',e.target.value)}/></label><label>欢迎语<textarea value={bot.welcome} onChange={e=>onChange('welcome',e.target.value)}/></label><label>标签<TagsField tags={bot.tags} onChange={value=>onChange('tags',value)}/></label><Visibility value={bot.visibility||'public'} onChange={value=>onChange('visibility',value)}/></div>}
const voices=[
  {id:'narration',name:'旁白',initial:'N',tags:['全部','沉静','叙述']},
  {id:'bold-elder',name:'沉稳长者',initial:'B',tags:['全部','男性','沉稳','雄辩']},
  {id:'brave-pal',name:'热血伙伴',initial:'P',tags:['全部','男性','活泼','真诚']},
  {id:'gentle-queen',name:'温柔女王',initial:'Q',tags:['全部','女性','温柔','优雅']},
  {id:'strong-leader',name:'坚定领袖',initial:'L',tags:['全部','男性','坚定','有力']},
  {id:'sharp-noble',name:'锋利贵族',initial:'S',tags:['全部','男性','疏离','优雅']},
  {id:'cheerful-girl',name:'欢快少女',initial:'C',tags:['全部','女性','活泼','温暖']},
];
const voiceFilters=['全部','沉静','坚定','优雅','活泼'];
const parseExamples=value=>{
  if(!value)return [{user:'',bot:''}];
  try{
    const parsed=JSON.parse(value);
    if(Array.isArray(parsed)&&parsed.length)return parsed.map(item=>typeof item==='string'?{user:'',bot:item}:{user:String(item?.user||item?.prompt||''),bot:String(item?.bot||item?.response||item?.assistant||'')});
    if(parsed&&typeof parsed==='object')return [{user:String(parsed.user||parsed.prompt||''),bot:String(parsed.bot||parsed.response||parsed.assistant||'')}];
  }catch{}
  return [{user:'',bot:String(value)}];
};
const stringifyExamples=rows=>JSON.stringify(rows.filter(row=>row.user.trim()||row.bot.trim()),null,2);
function VoiceModal({value,onClose,onApply}){const [filter,setFilter]=useState('全部');const [selected,setSelected]=useState(value||'narration');const filtered=voices.filter(voice=>filter==='全部'||voice.tags.includes(filter));const choose=voice=>{setSelected(voice.id);onApply(voice.id);onClose();};return <div className="advanced-modal-backdrop"><section className="advanced-modal voice-modal" role="dialog" aria-modal="true" aria-label="选择声音"><header><button type="button" className="advanced-back" onClick={onClose} aria-label="关闭声音选择"><ChevronLeft size={18}/></button><h2>Voice</h2><button type="button" className="advanced-close" onClick={onClose} aria-label="关闭"><X size={18}/></button></header><nav className="voice-filters">{voiceFilters.map(item=><button type="button" key={item} className={filter===item?'selected':''} onClick={()=>setFilter(item)}>{item}</button>)}</nav><div className="voice-list">{filtered.map(voice=><button type="button" key={voice.id} className={'voice-option '+(selected===voice.id?'selected':'')} onClick={()=>choose(voice)}><span className="voice-avatar">{voice.initial}</span><span><b>{voice.name}</b><small>{voice.tags.filter(tag=>tag!=='全部').join(' · ')}</small></span><Play size={15} fill="currentColor"/></button>)}</div></section></div>}
function ExamplesModal({value,onClose,onApply}){const [rows,setRows]=useState(()=>parseExamples(value));const update=(index,key,text)=>setRows(current=>current.map((row,rowIndex)=>rowIndex===index?{...row,[key]:text}:row));const add=()=>setRows(current=>[...current,{user:'',bot:''}]);return <div className="advanced-modal-backdrop"><section className="advanced-modal examples-modal" role="dialog" aria-modal="true" aria-label="编辑示例对话"><header><span/><h2>Example conversations</h2><button type="button" className="advanced-close" onClick={onClose} aria-label="关闭"><X size={18}/></button></header><div className="examples-tip">🔔 示例对话帮助 Bot 模仿你期待的文本结构与表达方式。</div><div className="example-rows">{rows.map((row,index)=><section className="example-pair" key={index}><textarea className="example-user" value={row.user} onChange={event=>update(index,'user',event.target.value)} placeholder="用户先说什么？"/><textarea className="example-bot" value={row.bot} onChange={event=>update(index,'bot',event.target.value)} placeholder="Bot 会如何回应？"/></section>)}</div><button type="button" className="add-example" onClick={add}><Plus size={14}/>添加一组对话</button><footer><button type="button" className="examples-confirm" onClick={()=>{onApply(stringifyExamples(rows));onClose();}}>继续</button></footer></section></div>}
function Advanced({bot,onChange}){const [voiceOpen,setVoiceOpen]=useState(false);const [examplesOpen,setExamplesOpen]=useState(false);const selectedVoice=voices.find(voice=>voice.id===(bot.voice||'narration'))||voices[0];return <div className="advanced-form"><label>Voice<button type="button" className="advanced-field" onClick={()=>setVoiceOpen(true)}><span className="voice-avatar compact">{selectedVoice.initial}</span><span><b>{selectedVoice.name}</b><small>选择 Bot 的表达声音</small></span><ChevronRight size={18}/></button></label><label>Example conversations<button type="button" className="advanced-field examples-field" onClick={()=>setExamplesOpen(true)}><span><b>编辑示例对话</b><small>{parseExamples(bot.examples).filter(row=>row.user||row.bot).length?'已添加示例对话':'让 Bot 学习你期待的表达方式'}</small></span><ChevronRight size={18}/></button></label>{voiceOpen&&<VoiceModal value={bot.voice} onClose={()=>setVoiceOpen(false)} onApply={value=>onChange('voice',value)}/>} {examplesOpen&&<ExamplesModal value={bot.examples} onClose={()=>setExamplesOpen(false)} onApply={value=>onChange('examples',value)}/>}</div>}
function ImagePage({art,onPreview,onSetCover,canSetCover}){const legacy=Array.isArray(art.data?.images)?[{id:art.data.task_id||'legacy',title:art.title,images:art.data.images}]:art.data?.url?[{id:'legacy',title:art.title,images:[{id:'legacy',title:art.title,url:art.data.url}]}]:[];const batches=Array.isArray(art.data?.batches)?art.data.batches:legacy;return batches.length?<div className="image-library">{batches.map(batch=><section className="image-batch" key={batch.id}><header><b>{batch.title}</b><small>{batch.images?.length||0} 张候选</small></header><div className="image-grid">{(batch.images||[]).map((image,index)=><article key={image.id||image.url}><button type="button" className="image-preview" onClick={()=>onPreview?.(image.url)}><img src={image.url} alt={image.title||batch.title+' '+(index+1)}/><b>{image.title||`候选 ${index+1}`}</b></button><button type="button" className="set-cover-action" disabled={!canSetCover} onClick={()=>onSetCover?.(image.url)} title={canSetCover?'将这张图设为当前 Bot 封面':'请先选择一个 Bot'}>设为封面</button></article>)}</div></section>)}</div>:<div className="image-empty"><Image size={22}/><b>暂无图片结果</b><small>图片任务完成后，真实图片地址会显示在这里。</small></div>}
export function RightViewer({artifacts,activeArtifact,onOpen,onClose,onCloseBrowser,expanded,onToggleExpand,onResizeStart,bot,botDraft,botDirty,onBotChange,onSaveBot,onRevertBot,onUpdate,onCreateText,onPreviewImage,onSetCover}){
  const art=artifacts.find(a=>a.id===activeArtifact);
  const normalArtifacts=artifacts.filter(a=>!a.type.startsWith('bot_'));
  const tabLabel=a=>a.title;
  const editingBot=Boolean(bot)&&activeArtifact===`bot-editor:${bot.id}`;
  return <aside className={'artifact-browser '+(editingBot?'bot-editor-open ':'')}><button type="button" className="artifact-resize-handle" onPointerDown={event=>{event.preventDefault();onResizeStart?.();}} aria-label="拖动调整编辑器宽度" title="拖动调整编辑器宽度" disabled={expanded}><GripVertical size={16}/></button><header className="artifact-navigation"><nav className="artifact-tabs">{bot&&<button type="button" className={editingBot?'active':''} onClick={()=>onOpen(`bot-editor:${bot.id}`)}><UserRound size={14}/><span>Bot 编辑</span>{botDirty&&<i className="dirty-dot"/>}</button>}{normalArtifacts.map(a=>{const Icon=(meta[a.type]||meta.other).icon;return <button type="button" className={a.id===activeArtifact?'active':''} key={a.id} onClick={()=>onOpen(a.id)} title={a.title}><Icon size={14}/><span>{tabLabel(a)}</span></button>})}</nav><div className="artifact-navigation-actions"><button type="button" className="artifact-browser-expand" onClick={onToggleExpand} aria-label={expanded?'收起编辑器':'展开编辑器'} title={expanded?'收起编辑器':'展开编辑器'}>{expanded?<Minimize2 size={16}/>:<Maximize2 size={16}/>}</button><button type="button" className="artifact-browser-close" onClick={onCloseBrowser} aria-label="关闭右侧工作页" title="关闭工作页"><X size={17}/></button></div></header><div className="artifact-content">{editingBot?<><BotEditor bot={bot} draft={botDraft} dirty={botDirty} onChange={onBotChange} onPreview={onPreviewImage} /><BotSaveBar dirty={botDirty} onSave={onSaveBot} onRevert={onRevertBot}/></>:!art?<div className="artifact-empty"><div className="artifact-empty-icon"><FolderOpen size={22}/></div><b>资源区为空</b><small>图片、文本和其他创作成果会在需要时出现在这里。</small></div>:<ArtifactPage art={art} onUpdate={onUpdate} onPreview={onPreviewImage} onSetCover={onSetCover} canSetCover={Boolean(bot)}/>}</div></aside>
}
function BotEditor({bot,draft,dirty,onChange,onPreview}){const [previewOpen,setPreviewOpen]=useState(false);return <section className="artifact-page bot-editor"><header><span className="artifact-type bot_basic"><UserRound size={15}/>Bot 编辑</span><h3>{bot.name}</h3><p>{dirty?'本地草稿未保存；确认后才会更新 Bot。':'所有修改已保存'}</p></header><section className="bot-editor-section"><h4>基础信息</h4><Basic bot={draft} onChange={onChange} onPreview={onPreview}/></section><section className="bot-editor-section"><div className="bot-editor-section-head"><h4>内容设定</h4><button type="button" className="content-expand" onClick={()=>setPreviewOpen(true)} title="放大查看内容设定"><Expand size={13}/>放大查看</button></div><div className="artifact-editor"><label>内容设定<textarea value={draft.content||''} onChange={event=>onChange('content',event.target.value)}/></label></div></section><section className="bot-editor-section"><h4>高级设置</h4><Advanced bot={draft} onChange={onChange}/></section>{previewOpen&&<ContentPreviewModal content={draft.content||''} onChange={value=>onChange('content',value)} onClose={()=>setPreviewOpen(false)}/>}</section>}
function BotSaveBar({dirty,onSave,onRevert}){return <footer className="bot-editor-footer"><div><span className={dirty?'dirty':'saved'}>{dirty?'● 有未保存修改':'● 已保存'}</span><small>{dirty?'当前修改只保留在本地草稿。':'当前内容与已保存的 Bot 一致。'}</small></div><div><button type="button" onClick={onRevert} disabled={!dirty}>撤销修改</button><button type="button" className="primary" onClick={onSave} disabled={!dirty}>确认并保存修改</button></div></footer>}
function TextArtifactEditor({art,onUpdate}){const initial=String(art.data??art.preview??'');const [value,setValue]=useState(initial);const [saving,setSaving]=useState(false);useEffect(()=>setValue(initial),[art.id,initial]);const dirty=value!==initial;const save=async()=>{if(!dirty||saving)return;setSaving(true);try{await onUpdate(art.id,{data:value});}finally{setSaving(false);}};return <div className="artifact-editor text-artifact-editor"><label>文本内容<textarea value={value} onChange={event=>setValue(event.target.value)} aria-label={`编辑文本「${art.title}」`}/></label><footer><small>{dirty?'有未保存修改':'可直接编辑此文本页。'}</small><button type="button" className="primary" disabled={!dirty||saving} onClick={save}>{saving?'保存中…':'保存修改'}</button></footer></div>}
function ArtifactPage({art,onUpdate,onPreview,onSetCover,canSetCover}){const type=meta[art.type]||meta.other;const Icon=type.icon;return <section className="artifact-page"><header><span className={'artifact-type '+art.type}><Icon size={15}/>{type.label}</span><h3>{art.title}</h3>{art.description&&<p>{art.description}</p>}</header>{['image','image_library'].includes(art.type)&&<ImagePage art={art} onPreview={onPreview} onSetCover={onSetCover} canSetCover={canSetCover}/>} {art.type==='text'&&<TextArtifactEditor art={art} onUpdate={onUpdate}/>} {['code','file','other'].includes(art.type)&&<pre className={art.type==='code'?'code-preview':''}>{renderData(art.data??art.preview)}</pre>}</section>}
