import {FileText,Image as ImageIcon,Save,UserRound} from 'lucide-react';
import {useEffect,useRef,useState} from 'react';
import {BottomSheet} from './BottomSheet';
import {api} from '../lib/api';

const iconFor=artifact=>artifact.type==='image_library'||artifact.type==='image'?<ImageIcon size={19}/>:<FileText size={19}/>;
const imagesFor=artifact=>artifact.type==='image_library'?(artifact.data?.batches||[]).flatMap(batch=>batch.images||[]):artifact.type==='image'?[artifact.data||artifact]:[];
const botDraft=bot=>({name:bot?.basic?.name||'',intro:bot?.basic?.intro||'',welcome:bot?.basic?.welcome||'',tags:bot?.basic?.tags||[],visibility:bot?.basic?.visibility||'public',cover_url:bot?.basic?.cover_url||'',content:bot?.content||'',voice:bot?.advanced?.voice||'narration',examples:bot?.advanced?.examples||''});

export function ResourceSheet({open,onClose,artifacts,onUpdate,bot,onBotUpdated,onPreviewImage,coverCandidate,onSetCover,onCoverConsumed}){
  const [selectedId,setSelectedId]=useState(null);
  const [botDrafts,setBotDrafts]=useState({});
  const selected=artifacts.find(item=>item.id===selectedId)||null;
  useEffect(()=>{if(!open)setSelectedId(null)},[open]);
  useEffect(()=>{if(open&&bot&&coverCandidate)setSelectedId('bot-editor')},[open,bot?.id,coverCandidate]);
  useEffect(()=>{if(bot)setBotDrafts(current=>({...current,[bot.id]:botDraft(bot)}))},[bot?.id,bot?.updated_at]);
  const editorDraft=bot?(botDrafts[bot.id]||botDraft(bot)):null;
  const editorDirty=bot?JSON.stringify(editorDraft)!==JSON.stringify(botDraft(bot)):false;
  const setEditorDraft=next=>{if(bot)setBotDrafts(current=>({...current,[bot.id]:typeof next==='function'?next(current[bot.id]||botDraft(bot)):next}))};
  if(selectedId==='bot-editor'&&bot)return <BotEditor bot={bot} draft={editorDraft} setDraft={setEditorDraft} onBack={()=>setSelectedId(null)} onClose={onClose} onBotUpdated={onBotUpdated} coverCandidate={coverCandidate} onCoverConsumed={onCoverConsumed}/>;
  if(selected)return <ResourceDetail artifact={selected} onBack={()=>setSelectedId(null)} onClose={onClose} onUpdate={onUpdate} onPreviewImage={onPreviewImage} canSetCover={Boolean(bot)} onSetCover={onSetCover}/>;
  return <BottomSheet open={open} title="资源区" onClose={onClose}><ResourceList artifacts={artifacts} bot={bot} botDirty={editorDirty} onSelect={setSelectedId}/></BottomSheet>;
}
function ResourceList({artifacts,bot,botDirty,onSelect}){return <div className="resource-list">{bot&&<button className="resource-row bot-resource-row" onClick={()=>onSelect('bot-editor')}><i><UserRound size={19}/></i><span><b>编辑 {bot.basic?.name||'当前 Bot'}</b><small>{botDirty?'有未保存修改':'基础信息、内容设定和高级设置'}</small></span>{botDirty&&<strong className="dirty-dot"/>}<em>›</em></button>}{artifacts.length?artifacts.map(item=><button className="resource-row" key={item.id} onClick={()=>onSelect(item.id)}><i>{iconFor(item)}</i><span><b>{item.title}</b><small>{item.type==='image_library'?'图片资源':item.type==='text'?'文本 · 可继续编辑':'创作成果 · 点击查看'}</small></span><em>›</em></button>):<p>还没有资源。对话中生成的图片、文本和 Bot 内容会出现在这里。</p>}</div>}
function BotEditor({bot,draft,setDraft,onBack,onClose,onBotUpdated,coverCandidate,onCoverConsumed}){
  const [saving,setSaving]=useState(false);const [error,setError]=useState('');const inputRef=useRef(null);
  const original=JSON.stringify(botDraft(bot));const dirty=JSON.stringify(draft)!==original;
  useEffect(()=>{if(coverCandidate)setDraft(current=>({...current,cover_url:coverCandidate}))},[coverCandidate]);
  const change=(key,value)=>setDraft(current=>({...current,[key]:value}));
  const upload=async event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;try{const data_url=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});const {attachment}=await api.uploadImage({name:file.name,mime_type:file.type,data_url});change('cover_url',attachment.url)}catch(cause){setError(cause.message)}};
  const save=async()=>{if(!dirty||saving||!draft.name.trim())return;setSaving(true);setError('');try{const {bot:updated}=await api.updateBot(bot.id,[{area:'basic',operation:'replace',value:{...bot.basic,name:draft.name.trim(),intro:draft.intro,welcome:draft.welcome,tags:draft.tags,visibility:draft.visibility,cover_url:draft.cover_url},reason:'移动端保存 Bot 编辑'},{area:'content',operation:'replace',value:draft.content,reason:'移动端保存 Bot 编辑'},{area:'advanced',operation:'replace',value:{...bot.advanced,voice:draft.voice,examples:draft.examples},reason:'移动端保存 Bot 编辑'}]);onBotUpdated(updated);onCoverConsumed?.()}catch(cause){setError(cause.message)}finally{setSaving(false)}};
  return <BottomSheet open title="编辑 Bot" onClose={onClose} actions={<button type="button" className="detail-back" onClick={onBack} aria-label="返回资源列表">‹</button>}><section className="bot-editor-mobile"><header><span><UserRound size={16}/>BOT 编辑</span><b>{bot.basic?.name||'未命名 Bot'}</b></header>{error&&<p className="editor-error">{error}</p>}<label className="cover-mobile"><span>封面</span><div>{draft.cover_url?<img src={draft.cover_url} alt="Bot 封面"/>:<i><ImageIcon size={22}/></i>}<input ref={inputRef} type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={upload}/><button type="button" onClick={()=>inputRef.current?.click()}>上传 / 更换封面</button></div></label><fieldset><legend>基础信息</legend><label>名称 <em>*</em><input value={draft.name} onChange={event=>change('name',event.target.value)}/></label><label>简介<textarea value={draft.intro} onChange={event=>change('intro',event.target.value)}/></label><label>欢迎语<textarea value={draft.welcome} onChange={event=>change('welcome',event.target.value)}/></label><label>标签（最多 5 个，以逗号分隔）<input value={draft.tags.join(', ')} onChange={event=>change('tags',event.target.value.split(/[,，]/).map(x=>x.trim()).filter(Boolean).slice(0,5))}/></label><div className="visibility-mobile"><span>可见范围</span><button type="button" className={draft.visibility==='public'?'selected':''} onClick={()=>change('visibility','public')}>公开</button><button type="button" className={draft.visibility==='private'?'selected':''} onClick={()=>change('visibility','private')}>私有</button></div></fieldset><fieldset><legend>内容设定</legend><textarea className="content-mobile" value={draft.content} onChange={event=>change('content',event.target.value)} placeholder="写入角色、世界观、互动规则与开场设定…"/></fieldset><fieldset><legend>高级设置</legend><label>Voice<select value={draft.voice} onChange={event=>change('voice',event.target.value)}><option value="narration">旁白叙事</option><option value="gentle">温柔陪伴</option><option value="lively">活泼互动</option><option value="cool">冷静克制</option></select></label><label>示例对话<textarea value={draft.examples} onChange={event=>change('examples',event.target.value)} placeholder="用户：…\nBot：…"/></label></fieldset><footer><button type="button" onClick={()=>setDraft(botDraft(bot))} disabled={!dirty||saving}>撤销修改</button><button type="button" className="resource-save" disabled={!dirty||saving||!draft.name.trim()} onClick={save}><Save size={15}/>{saving?'保存中…':'确认并保存'}</button></footer></section></BottomSheet>;
}
function ResourceDetail({artifact,onBack,onClose,onUpdate,onPreviewImage,canSetCover,onSetCover}){const [value,setValue]=useState(String(artifact.data??artifact.preview??''));const [saving,setSaving]=useState(false);useEffect(()=>setValue(String(artifact.data??artifact.preview??'')),[artifact.id,artifact.data,artifact.preview]);const images=imagesFor(artifact);const save=async()=>{if(saving||value===String(artifact.data??artifact.preview??''))return;setSaving(true);try{await onUpdate(artifact.id,{data:value})}finally{setSaving(false)}};return <BottomSheet open title={artifact.title} onClose={onClose} actions={<button type="button" className="detail-back" onClick={onBack} aria-label="返回资源列表">‹</button>}><div className="resource-detail">{artifact.description&&<p>{artifact.description}</p>}{images.length?<div className="resource-images">{images.map((image,index)=><figure key={image.id||image.url||index}><button type="button" className="resource-image-preview" onClick={()=>onPreviewImage?.(image.url)}><img src={image.url} alt={image.title||`${artifact.title} 图片 ${index+1}`}/></button><figcaption>{image.title||`候选 ${index+1}`}</figcaption><button type="button" className="set-cover-mobile" disabled={!canSetCover} onClick={()=>onSetCover?.(image.url)}>{canSetCover?'设为 Bot 封面':'先选择一个 Bot'}</button></figure>)}</div>:artifact.type==='text'?<><textarea aria-label={`编辑文本「${artifact.title}」`} value={value} onChange={event=>setValue(event.target.value)}/><button type="button" className="resource-save" disabled={saving||value===String(artifact.data??artifact.preview??'')} onClick={save}><Save size={15}/>{saving?'保存中…':'保存修改'}</button></>:<pre>{value||'暂无可预览内容'}</pre>}</div></BottomSheet>}
